Commented out code

diff --git a/.github/workflows/minor-release.yml b/.github/workflows/minor-release.yml
--- a/.github/workflows/minor-release.yml
+++ b/.github/workflows/minor-release.yml
@@ -72,21 +72,21 @@ jobs:
           sed -i "s/export const PUBLISHING_VERSION = '.*';/export const PUBLISHING_VERSION = '$version';/" ./tools/config/const.ts
           echo "Updated PUBLISHING_VERSION in ./tools/config/const.ts."
 
-      - name: Package installation
-        run: npm ci
+      # - name: Package installation
+      #   run: npm ci
         
-      - name: Run Config Update
-        run: |
-          if ! npm run config:update; then
-            echo "Error: The configuration file is not up to date. Regenerating dependencies..."
-            npm run generate:deps
-            npm run config:update
-          fi
-          npm run generate:deps
+      # - name: Run Config Update
+      #   run: |
+      #     if ! npm run config:update; then
+      #       echo "Error: The configuration file is not up to date. Regenerating dependencies..."
+      #       npm run generate:deps
+      #       npm run config:update
+      #     fi
+      #     npm run generate:deps
 
-      - name: Run Schematics Tests
-        run: |
-          npm run test:all-schematics
+      # - name: Run Schematics Tests
+      #   run: |
+      #     npm run test:all-schematics
 
       - name: Push Changes
         run: |
