rm creation of new branch

diff --git a/.github/workflows/minor-release.yml b/.github/workflows/minor-release.yml
--- a/.github/workflows/minor-release.yml
+++ b/.github/workflows/minor-release.yml
@@ -59,6 +59,11 @@ jobs:
 
           echo "Checking for existence of the branch: $release_branch"
 
+          if git ls-remote --heads origin "$release_branch" | grep -q "$release_branch"; then
+            echo "Error: Branch $release_branch already exists. Please check the branch before proceeding."
+            exit 1
+          fi
+
       - name: Update SCSS Versioning
         run: |
           major=${{ env.major }}
@@ -74,6 +79,19 @@ jobs:
           version="${{ env.major }}.${{ env.minor }}.${{ env.patch }}"
           sed -i "s/export const PUBLISHING_VERSION = '.*';/export const PUBLISHING_VERSION = '$version';/" ./tools/config/const.ts
           echo "Updated PUBLISHING_VERSION in ./tools/config/const.ts."
+
+      - name: Package installation
+        run: npm ci
+        
+      - name: Run NPM Commands
+        run: |
+          if ! npm run config:update; then
+            echo "Error: The configuration file is not up to date. Regenerating dependencies..."
+            npm run generate:deps
+            npm run config:update
+          fi
+          npm run generate:deps
+          npm run test:all-schematics
 
       - name: Create Pull Request
         uses: peter-evans/create-pull-request@v6
