Update release workflow to use vesrion parts from env variables defined at the beginning instead of input

diff --git a/.github/workflows/release-minor.yml b/.github/workflows/release-minor.yml
--- a/.github/workflows/release-minor.yml
+++ b/.github/workflows/release-minor.yml
@@ -34,34 +34,41 @@ jobs:
           fi
           
           IFS='.' read -ra ADDR <<< "$version_part"
-          major=${ADDR[0]}
-          minor=${ADDR[1]}
-          patch=${ADDR[2]}
-          release_branch="release-${major}.${minor}.${patch}"
+          echo "major=${ADDR[0]}" >> $GITHUB_ENV
+          echo "minor=${ADDR[1]}" >> $GITHUB_ENV
+          echo "patch=${ADDR[2]}" >> $GITHUB_ENV
+          release_branch="release-${ADDR[0]}.${ADDR[1]}.${ADDR[2]}"
           
           if [[ -n $prerelease ]]; then
             release_branch="${release_branch}-${prerelease// /-}"
           fi
 
           echo "RELEASE_BRANCH=$release_branch" >> $GITHUB_ENV
-          git checkout -b "release-${{ github.event.inputs.version }}"
+
+          echo "Checking for existence of the branch: $release_branch"
+          if git ls-remote --heads origin "$release_branch" | grep -q "$release_branch"; then
+            echo "Error: Branch $release_branch already exists. Please check the branch before proceeding."
+            exit 1
+          else
+            echo "Branch $release_branch does not exist. Creating new one."
+            git checkout -b "$release_branch"
 
       - name: Update SCSS Versioning
         run: |
-            major=$(echo "${{ github.event.inputs.version }}" | cut -d '.' -f 1)
-            minor=$(echo "${{ github.event.inputs.version }}" | cut -d '.' -f 2)
-            patch=$(echo "${{ github.event.inputs.version }}" | cut -d '.' -f 3 | cut -d '-' -f 1)
-            sed -i "s/major: [0-9]\\{1,\\},/major: $major,/" projects/storefrontstyles/scss/_versioning.scss
-            sed -i "s/minor: [0-9]\\{1,\\},/minor: $minor,/" projects/storefrontstyles/scss/_versioning.scss
-            sed -i "s/patch: [0-9]\\{1,\\},/patch: $patch,/" projects/storefrontstyles/scss/_versioning.scss
-            echo "Updated versions in projects/storefrontstyles/scss/_versioning.scss."
+          major=${{ env.major }}
+          minor=${{ env.minor }}
+          patch=${{ env.patch }}
+          sed -i "s/major: [0-9]\\{1,\\},/major: $major,/" projects/storefrontstyles/scss/_versioning.scss
+          sed -i "s/minor: [0-9]\\{1,\\},/minor: $minor,/" projects/storefrontstyles/scss/_versioning.scss
+          sed -i "s/patch: [0-9]\\{1,\\},/patch: $patch,/" projects/storefrontstyles/scss/_versioning.scss
+          echo "Updated versions in projects/storefrontstyles/scss/_versioning.scss."
 
       - name: Update Publishing Version
         run: |
-          version="${{ github.event.inputs.version }}"
+          version="${{ env.major }}.${{ env.minor }}.${{ env.patch }}"
           sed -i "s/export const PUBLISHING_VERSION = '.*';/export const PUBLISHING_VERSION = '$version';/" ./tools/config/const.ts
           echo "Updated PUBLISHING_VERSION in ./tools/config/const.ts."
-        
+
       - name: Run NPM Commands
         run: |
           if ! npm run config:update; then
@@ -71,17 +78,17 @@ jobs:
           fi
           npm run generate:deps
           npm run test:all-schematics
-  
+
       - name: Push Changes
         run: |
           git add .
-          git commit -m "Release ${{ github.event.inputs.version }}"
-          git push origin HEAD:"release-${{ github.event.inputs.version }}"
-  
+          git commit -m "Release "${{ env.RELEASE_BRANCH }}"
+          git push origin HEAD:"$release_branch"
+
       - name: Create Pull Request
         uses: peter-evans/create-pull-request@v6
         with:
-          branch: "release-${{ github.event.inputs.version }}" 
+          branch: "${{ env.RELEASE_BRANCH }}" 
           delete-branch: true 
           title: "Release ${{ github.event.inputs.version }}"
           body: "Automated pull request to merge the release branch into develop."
