feat: set productiveBranch when copying from public to private repo (#16253)
Set the productiveBranch value to the name of the copied branch when copying from public to private repository

closes: https://jira.tools.sap/browse/CXSPA-1483

diff --git a/.github/workflows/repo-sync.yml b/.github/workflows/repo-sync.yml
--- a/.github/workflows/repo-sync.yml
+++ b/.github/workflows/repo-sync.yml
@@ -28,6 +28,7 @@ jobs:
       - name: Include remaining pipeline files to the private remote's branch
         run: |
           SONAR_PATH="./sonar-project.properties"
+          PIPELINE_CONFIG_PATH="./.pipeline/config.yml"
 
           echo "---------------------------------------------------------------------------------------------------------------------------"
           echo "Clone repo"
@@ -42,6 +43,22 @@ jobs:
           echo "Get files from other branch"
 
           git checkout origin/sap-pipeline-files -- .
+
+          echo "---------------------------------------------------------------------------------------------------------------------------"
+          echo "Configure pipeline"
+
+          sed -i "s%productiveBranch:%productiveBranch: '${{ github.event.inputs.branch_to_sync || env.DEFAULT_BRANCH_TO_SYNC }}'%gi" $PIPELINE_CONFIG_PATH
+
+          echo "---------------------------------------------------------------------------------------------------------------------------"
+          echo "Verify productiveBranch has been updated with the synched branch name"
+
+          if grep -Fq "productiveBranch: '${{ github.event.inputs.branch_to_sync || env.DEFAULT_BRANCH_TO_SYNC }}'" $PIPELINE_CONFIG_PATH
+          then
+              echo "Branch name has successfully been added to the productiveBranch"
+          else
+              echo "Error. Branch name has NOT been added to the productiveBranch"
+              exit 1
+          fi
 
           echo "---------------------------------------------------------------------------------------------------------------------------"
           echo "Configure sonar"
